name: unittest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest
    - name: Running test on data_formating
      working-directory: data_formating
      run: |
        coverage run -m pytest
    - name: Running test on railway_solvers
      working-directory: railway_solvers
      run: |
        coverage run -m pytest
    
    